name: Configure the dotnet appsettings.tmpl.json
description: 'Uses a bunch of secrets and attempts to shim a dotnet settings tmpl'
branding:
  icon: 'settings'
  color: 'green'
inputs:
  secrets:
    description: Secrets (toJson(secrets))
    required: true
    type: string
  vars:
    description: Vars (toJson(vars))
    required: true
    type: string
  env:
    description: Env (toJson(env))
    required: true
    type: string
  pathToTemplate:
    description: This is the path to the tmpl file to configure (default - ./repo-name/appsettings.tmpl.json)
    required: false
    type: string
  renameTo:
    description: What env we should rename this appsettings to (e.g. appsettings.tmpl.json -> appsettings.Production.json)
    required: false
    type: string
  removeOtherSettingsFiles:
    description: Should we remove other appsettings files?
    required: false
    type: boolean
  

output:
  settingsJsonString:
    description: Fully replaced settings file in json string format (use JSON.parse( needs.job.outputs.settingsJsonString ) to/use)
runs:
  using: 'node16'
  main: 'dist/index.js'
